/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario_con_bd;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class entre_code extends javax.swing.JFrame {
    /**
     * Creates new form entre_code
     */
    public entre_code() {
        initComponents();
    }
    static javax.swing.JFrame padre;
    public entre_code(javax.swing.JFrame padre) {
        this.padre = padre;
        initComponents();
    }
    Utilidades ut = new Utilidades();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldSegundo = new javax.swing.JTextField();
        jTextFieldPrimero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButtonAceptar.setMnemonic('a');
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setMnemonic('c');
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldSegundo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSegundoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSegundoKeyPressed(evt);
            }
        });

        jTextFieldPrimero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrimeroKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPrimeroKeyPressed(evt);
            }
        });

        jLabel1.setText("Entre");

        jLabel2.setText("y");

        jLabel3.setText("Mostrar lista por código");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                            .addComponent(jButtonCancelar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldSegundo)
                            .addComponent(jButtonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
//        ut.ceros(jTextFieldPrimero,6);
//        ut.ceros(jTextFieldSegundo, 6);
//        if(jTextFieldPrimero.getText().equals(jTextFieldSegundo.getText())){
//            JOptionPane.showMessageDialog(this, "ERROR\nLos dos campos tienen los mismos valores.");
//        }else if(jTextFieldPrimero.getText().compareTo(jTextFieldSegundo.getText())>0){
//            Conexion.ejecutarInformeEC(jTextFieldSegundo.getText(),jTextFieldPrimero.getText()).setVisible(true);
//        }else{
//            Conexion.ejecutarInformeEC(jTextFieldPrimero.getText(),jTextFieldSegundo.getText()).setVisible(true);
//        }
//        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        padre.setEnabled(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldPrimeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrimeroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            ut.ceros(jTextFieldPrimero, 6);
            if(ut.comprobar(jTextFieldPrimero, "Codigo", 6)){
                JOptionPane.showMessageDialog(this, "Error\n Es un campo alfanumérico, sin caracteres especiales");
                jTextFieldPrimero.setText("");
            }else{
                jTextFieldSegundo.grabFocus();
            }
        }
    }//GEN-LAST:event_jTextFieldPrimeroKeyPressed

    private void jTextFieldSegundoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSegundoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            ut.ceros(jTextFieldSegundo, 6);
            if(ut.comprobar(jTextFieldSegundo, "Codigo", 6)){
                JOptionPane.showMessageDialog(this, "Error\n Es un campo alfanumérico, sin caracteres especiales");
                jTextFieldSegundo.setText("");
            }
        }
    }//GEN-LAST:event_jTextFieldSegundoKeyPressed

    private void jTextFieldPrimeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrimeroKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldPrimero,6, evt);
    }//GEN-LAST:event_jTextFieldPrimeroKeyTyped

    private void jTextFieldSegundoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSegundoKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldSegundo,6, evt);
    }//GEN-LAST:event_jTextFieldSegundoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entre_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entre_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entre_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entre_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entre_code(padre).setVisible(true);
            }
        });
    }
     protected void processWindowEvent(java.awt.event.WindowEvent e) {

        super.processWindowEvent(e);
        if (e.getID() == java.awt.event.WindowEvent.WINDOW_CLOSING) {
            padre.setEnabled(true);
        }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldPrimero;
    private javax.swing.JTextField jTextFieldSegundo;
    // End of variables declaration//GEN-END:variables
}
