/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario_con_bd;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    static javax.swing.JFrame padre;
    public Formulario(javax.swing.JFrame padre) {
        this.padre = padre;
        initComponents();
    }
    Utilidades ut = new Utilidades();
    Conexion cox = new Conexion();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelNIF = new javax.swing.JLabel();
        jTextFieldNIF = new javax.swing.JTextField();
        jTextFieldNIF_letra = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelDomicilio = new javax.swing.JLabel();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jLabelCP = new javax.swing.JLabel();
        jTextFieldCP = new javax.swing.JTextField();
        jLabelLocalidad = new javax.swing.JLabel();
        jTextFieldLocalidad = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelMovil = new javax.swing.JLabel();
        jTextFieldMovil = new javax.swing.JTextField();
        jLabelFax = new javax.swing.JLabel();
        jTextFieldFax = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Altas = new javax.swing.JMenuItem();
        Bajas = new javax.swing.JMenuItem();
        Modificaciones = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Volver = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jMenuItemConsultaPorCodigo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de almacén Clientes");
        setResizable(false);

        jLabelCodigo.setText("Código");

        jTextFieldCodigo.setToolTipText("");
        jTextFieldCodigo.setEnabled(false);
        jTextFieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyTyped(evt);
            }
        });

        jLabelNIF.setText("N.I.F.");

        jTextFieldNIF.setEnabled(false);
        jTextFieldNIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNIFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNIFKeyTyped(evt);
            }
        });

        jTextFieldNIF_letra.setEditable(false);
        jTextFieldNIF_letra.setToolTipText("");
        jTextFieldNIF_letra.setEnabled(false);

        jLabelNombre.setText("Nombre");

        jTextFieldNombre.setEnabled(false);
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });

        jLabelApellidos.setText("Apellidos");

        jTextFieldApellidos.setToolTipText("");
        jTextFieldApellidos.setEnabled(false);
        jTextFieldApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosKeyTyped(evt);
            }
        });

        jLabelDomicilio.setText("Domicilio");

        jTextFieldDomicilio.setEnabled(false);
        jTextFieldDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDomicilioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDomicilioKeyTyped(evt);
            }
        });

        jLabelCP.setText("C.P.");

        jTextFieldCP.setEnabled(false);
        jTextFieldCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCPKeyTyped(evt);
            }
        });

        jLabelLocalidad.setText("Localidad");

        jTextFieldLocalidad.setEnabled(false);
        jTextFieldLocalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLocalidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLocalidadKeyTyped(evt);
            }
        });

        jLabelTelefono.setText("Teléfono");

        jTextFieldTelefono.setEnabled(false);
        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyTyped(evt);
            }
        });

        jLabelMovil.setText("Móvil");

        jTextFieldMovil.setEnabled(false);
        jTextFieldMovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMovilKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMovilKeyTyped(evt);
            }
        });

        jLabelFax.setText("Fax");

        jTextFieldFax.setEnabled(false);
        jTextFieldFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFaxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFaxKeyTyped(evt);
            }
        });

        jLabelEmail.setText("Email");

        jTextFieldEmail.setEnabled(false);
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });

        jLabelTotal.setText("Total");

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setEnabled(false);

        jButtonAceptar.setMnemonic('A');
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setEnabled(false);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setMnemonic('C');
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalir.setMnemonic('s');
        jButtonSalir.setText("Salir");
        jButtonSalir.setEnabled(false);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jMenu1.setMnemonic('m');
        jMenu1.setText("Mantenimiento");

        Altas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        Altas.setMnemonic('a');
        Altas.setText("Altas");
        Altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltasActionPerformed(evt);
            }
        });
        jMenu1.add(Altas);

        Bajas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        Bajas.setMnemonic('b');
        Bajas.setText("Bajas");
        Bajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajasActionPerformed(evt);
            }
        });
        jMenu1.add(Bajas);

        Modificaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        Modificaciones.setMnemonic('m');
        Modificaciones.setText("Modificaciones");
        Modificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificacionesActionPerformed(evt);
            }
        });
        jMenu1.add(Modificaciones);
        jMenu1.add(jSeparator1);

        Volver.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        Volver.setMnemonic('r');
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jMenu1.add(Volver);

        jMenuBar1.add(jMenu1);

        jMenuConsulta.setMnemonic('o');
        jMenuConsulta.setText("Consulta");

        jMenuItemConsultaPorCodigo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemConsultaPorCodigo.setMnemonic('p');
        jMenuItemConsultaPorCodigo.setText("Por código");
        jMenuItemConsultaPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaPorCodigoActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsultaPorCodigo);

        jMenu3.setMnemonic('l');
        jMenu3.setText("Listado");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setMnemonic('p');
        jMenuItem6.setText("Por código");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setMnemonic('e');
        jMenuItem7.setText("Entre códigos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setMnemonic('g');
        jMenuItem8.setText("Gráficos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuConsulta.add(jMenu3);

        jMenuBar1.add(jMenuConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldApellidos)
                            .addComponent(jTextFieldDomicilio)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCodigo)
                                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNIF)
                                        .addGap(55, 55, 55))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNIF_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelApellidos)
                            .addComponent(jLabelDomicilio)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCP)
                                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLocalidad)
                                    .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTelefono)
                                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMovil)
                                    .addComponent(jTextFieldMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFax)
                                    .addComponent(jTextFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmail)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTotal)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldTotal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir)
                        .addGap(12, 12, 12)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jLabelNIF)
                    .addComponent(jLabelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNIF_letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabelApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelDomicilio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCP)
                    .addComponent(jLabelLocalidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jLabelMovil)
                    .addComponent(jLabelFax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void borrar(){
           // TODO add your handling code here:
        jTextFieldCodigo.setText("");
        jTextFieldNIF.setText("");
        jTextFieldNIF_letra.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellidos.setText("");
        jTextFieldDomicilio.setText("");
        jTextFieldCP.setText("");
        jTextFieldLocalidad.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldMovil.setText("");
        jTextFieldFax.setText("");
        jTextFieldEmail.setText("");
        jTextFieldCodigo.grabFocus();
    }
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        if(this.getTitle().equals("Gestión de almacén Clientes altas")||this.getTitle().equals("Gestión de almacén Clientes modificaciones")){
            String al = null;
            String error_campo = "";
           if(!(jTextFieldCodigo.getText().equals("")||
              jTextFieldNIF.getText().equals("")||
              jTextFieldNombre.getText().equals("")||
              jTextFieldApellidos.getText().equals("")||
              jTextFieldDomicilio.getText().equals("")||
              jTextFieldCP.getText().equals("")||
              jTextFieldLocalidad.getText().equals(""))){

               String tlf = "Este campo es exclusivamente numérico y debe tener 9 cifras";
               if(!jTextFieldEmail.getText().equals("")){
                    if( ut.comprobar(jTextFieldEmail, "Email",0)){
                 al = jLabelEmail.getText();
                    jTextFieldEmail.grabFocus();
                     error_campo = "Este campo solo admite letras y '_'\n el formato debe ser xxxx@xxx.xx";
                }
               }
               
                if(!jTextFieldFax.getText().equals("")){
                    if(ut.comprobar(jTextFieldFax,"Numero",9)){
                         
                        al = jLabelFax.getText();
                        jTextFieldFax.grabFocus();
                        error_campo = tlf;
                   }
                }

                if(!jTextFieldMovil.getText().equals("")){
                    if(ut.comprobar(jTextFieldMovil,"Numero",9)){
                         
                        al = jTextFieldMovil.getText();
                        jTextFieldMovil.grabFocus();
                        error_campo = tlf;
                   }
                }
                if(!jTextFieldTelefono.getText().equals("")){
                    if(ut.comprobar(jTextFieldTelefono,"Numero",9)){
                         
                        al = jTextFieldTelefono.getText();
                       jTextFieldTelefono.grabFocus();
                        error_campo = tlf;
                   }
                }
                if(ut.comprobar(jTextFieldLocalidad,"Apellidos",0)){
                  al = jLabelLocalidad.getText();
                  jTextFieldLocalidad.grabFocus();
                  error_campo = "Este campo solo admite letras y '-'";
                }
                if(ut.comprobar(jTextFieldCP,"Numero",5)){
                     al = jLabelCP.getText();
                    jTextFieldCP.grabFocus();
                    error_campo = "Este campo es exclusivamente numérico y debe tener 5 cifras";
                }
                 if(ut.comprobar(jTextFieldApellidos,"Apellidos",0)){
                     al = jLabelApellidos.getText();
                     jTextFieldApellidos.grabFocus();
                     error_campo = "Este campo solo admite letras y '-'";
                }
                if(ut.comprobar(jTextFieldNombre,"Nombre",0)){
                 al = jLabelNombre.getText();
                    jTextFieldNombre.grabFocus();
                 error_campo = "Este campo solo admite letras";
                }
                 if(ut.comprobar(jTextFieldNIF, "Numero",1)){
                    al = jLabelNIF.getText();
                    jTextFieldNIF.grabFocus();
                    error_campo = "Este campo es exclusivamente numérico";
                }else{
                    ut.ceros(jTextFieldNIF, 8);
                    jTextFieldNIF_letra.setText(ut.calculaLetra(Integer.parseInt(jTextFieldNIF.getText())));
                }
                if(ut.comprobar(jTextFieldCodigo, "Codigo", 1)){
                    al = jLabelCodigo.getText();
                    jTextFieldCodigo.grabFocus();
                     error_campo = "Este campo solo admite letras y números";
                }else{
                    ut.ceros(jTextFieldCodigo,6);
                }
                if(al!= null){
                    JOptionPane.showMessageDialog(null,"Error del campo "+al+"\n"+error_campo,"Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    try {
                         if(this.getTitle().equals("Gestión de almacén Clientes altas")){
                        cox.Alta(jTextFieldCodigo.getText(),
                                jTextFieldNIF.getText()+jTextFieldNIF_letra.getText(),
                                jTextFieldNombre.getText(),
                                jTextFieldApellidos.getText(),
                                jTextFieldDomicilio.getText(),
                                jTextFieldCP.getText(),
                                jTextFieldLocalidad.getText(),
                                jTextFieldTelefono.getText(),
                                jTextFieldMovil.getText(),
                                jTextFieldFax.getText(),
                                jTextFieldEmail.getText());
                         }else if(this.getTitle().equals("Gestión de almacén Clientes modificaciones")){
                             cox.Modificar(jTextFieldCodigo.getText(),
                                jTextFieldNIF.getText()+jTextFieldNIF_letra.getText(),
                                jTextFieldNombre.getText(),
                                jTextFieldApellidos.getText(),
                                jTextFieldDomicilio.getText(),
                                jTextFieldCP.getText(),
                                jTextFieldLocalidad.getText(),
                                jTextFieldTelefono.getText(),
                                jTextFieldMovil.getText(),
                                jTextFieldFax.getText(),
                                jTextFieldEmail.getText());
                         }
                    } catch (SQLException ex) {
                        Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this,"Formulario completado");
                    borrar();
                    habilitar(false,1);
                    jTextFieldCodigo.setEnabled(true);
                    jTextFieldCodigo.grabFocus();
                }
           }else{
               JOptionPane.showMessageDialog(null,"Hay que rellenar todos los campos salvo telefono, movil, fax y email","Error",JOptionPane.ERROR_MESSAGE);
               jTextFieldCodigo.grabFocus();
           }
        //AHORA HACEMOS LAS BAJAS    
        }else if(this.getTitle().equals("Gestión de almacén Clientes bajas")){
            try { 
               int res = JOptionPane.showConfirmDialog(this, "¿Está seguro de que quiere eliminar este registro?","Modificar registro",JOptionPane.YES_NO_OPTION);
                if(res == JOptionPane.YES_OPTION||res==JOptionPane.NO_OPTION){
                    habilitar(false,1);
                    jTextFieldCodigo.setEnabled(true);
                    jTextFieldCodigo.grabFocus();
                    if(res == JOptionPane.YES_OPTION){
                        cox.Baja(jTextFieldCodigo.getText());
                        JOptionPane.showMessageDialog(this, "El registro ha sido eliminado");
                    }
                    borrar();
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        borrar();
        habilitar(false,1);
        jTextFieldCodigo.setEnabled(true);
        jTextFieldCodigo.grabFocus();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldCodigo,6, evt);
    }//GEN-LAST:event_jTextFieldCodigoKeyTyped

    private void jTextFieldNIFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNIFKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldNIF,8, evt);
    }//GEN-LAST:event_jTextFieldNIFKeyTyped

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldNombre,15, evt);
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldApellidos, 35, evt);
    }//GEN-LAST:event_jTextFieldApellidosKeyTyped

    private void jTextFieldDomicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDomicilioKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldDomicilio, 40, evt);
    }//GEN-LAST:event_jTextFieldDomicilioKeyTyped

    private void jTextFieldCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCPKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldCP,5, evt);
    }//GEN-LAST:event_jTextFieldCPKeyTyped

    private void jTextFieldLocalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLocalidadKeyTyped
        // TODO add your handling code here:
         ut.num_carac(jTextFieldLocalidad,20, evt);
    }//GEN-LAST:event_jTextFieldLocalidadKeyTyped

    private void jTextFieldTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldTelefono, 9, evt);
    }//GEN-LAST:event_jTextFieldTelefonoKeyTyped

    private void jTextFieldMovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMovilKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldMovil,9, evt);
    }//GEN-LAST:event_jTextFieldMovilKeyTyped

    private void jTextFieldFaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFaxKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldFax,9, evt);
    }//GEN-LAST:event_jTextFieldFaxKeyTyped

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldEmail,20, evt);
    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    private void jTextFieldCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            ut.ceros(jTextFieldCodigo, 6);
            String code = jTextFieldCodigo.getText();
            if(this.getTitle().equals("Gestión de almacén Clientes altas")){
                try {
                    if(!cox.Consultar(code,"Clientes","Cli")){
                        habilitar(true,1);
                        jTextFieldCodigo.setEnabled(false);
                        jTextFieldNIF.grabFocus();
                    }else{
                        JOptionPane.showMessageDialog(this, "Este usuario ya existe");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }else if(this.getTitle().equals("Gestión de almacén Clientes bajas")){
                  try {
                    if(cox.Consultar(code,"Clientes","Cli")){
                        habilitar(true,2);
                        consultar(code);
                        jTextFieldCodigo.setEnabled(false);
                    }else{
                        JOptionPane.showMessageDialog(this, "Este usuario no existe");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(this.getTitle().equals("Gestión de almacén Clientes modificaciones")){
                try {
                    if(cox.Consultar(code,"Clientes","Cli")){
                        habilitar(true,1);
                        jTextFieldCodigo.setEnabled(false);
                        jTextFieldNIF.grabFocus();
                        consultar(code);
                        
                    }else{
                        JOptionPane.showMessageDialog(this, "Este usuario no existe");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(this.getTitle().equals("Gestión de almacén Clientes consultas")){
                try {
                    if(cox.Consultar(code,"Clientes","Cli")){
                        consultar(code);
                        
                    }else{
                        JOptionPane.showMessageDialog(this, "Este usuario no existe");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
               
            
        }
    }//GEN-LAST:event_jTextFieldCodigoKeyPressed
    private void consultar(String code) throws SQLException{
        ResultSet rs= cox.obtener(code,"Clientes","CodigoCli");
                        rs.next();
             
                        jTextFieldNIF.setText(rs.getString("NIF").substring(0,8));
                        jTextFieldNIF_letra.setText(rs.getString("NIF").substring(8));
                        jTextFieldNombre.setText(rs.getString("Nombre"));
                        jTextFieldApellidos.setText(rs.getString("Apellidos"));
                        jTextFieldDomicilio.setText(rs.getString("Domicilio"));
                        jTextFieldCP.setText(rs.getString("CP"));
                        jTextFieldLocalidad.setText(rs.getString("Localidad"));
                        jTextFieldTelefono.setText(rs.getString("Telefono"));
                        jTextFieldFax.setText(rs.getString("Fax"));
                        jTextFieldMovil.setText(rs.getString("Movil"));
                        jTextFieldEmail.setText(rs.getString("Email"));
    }
    private void jTextFieldNIFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNIFKeyPressed
        // TODO add your handling code here:
        int e = evt.getKeyCode();
         if(e== KeyEvent.VK_ENTER){
            jTextFieldNombre.grabFocus();
        }
    }//GEN-LAST:event_jTextFieldNIFKeyPressed

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldApellidos.grabFocus();
        }
    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    private void jTextFieldApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldDomicilio.grabFocus();
        }
    }//GEN-LAST:event_jTextFieldApellidosKeyPressed

    private void jTextFieldDomicilioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDomicilioKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldCP.grabFocus();
        }
    }//GEN-LAST:event_jTextFieldDomicilioKeyPressed

    private void jTextFieldCPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCPKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldLocalidad.grabFocus();
        }
    }//GEN-LAST:event_jTextFieldCPKeyPressed

    private void jTextFieldLocalidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLocalidadKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldTelefono.grabFocus();
        }
    }//GEN-LAST:event_jTextFieldLocalidadKeyPressed

    private void jTextFieldTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldMovil.grabFocus();
        }
    }//GEN-LAST:event_jTextFieldTelefonoKeyPressed

    private void jTextFieldMovilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMovilKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldFax.grabFocus();
        }
    }//GEN-LAST:event_jTextFieldMovilKeyPressed

    private void jTextFieldFaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFaxKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldEmail.grabFocus();
        }
    }//GEN-LAST:event_jTextFieldFaxKeyPressed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        padre.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_VolverActionPerformed

    private void AltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltasActionPerformed
        // TODO add your handling code here:
        this.setTitle("Gestión de almacén Clientes altas");
        habilitar(true,0);
        jTextFieldCodigo.grabFocus();
        hab_menu(false);
        
    }//GEN-LAST:event_AltasActionPerformed

    private void BajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajasActionPerformed
        // TODO add your handling code here:
        this.setTitle("Gestión de almacén Clientes bajas");
        habilitar(true,0);
        hab_menu(false);
        jTextFieldCodigo.grabFocus();
    }//GEN-LAST:event_BajasActionPerformed

    private void ModificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificacionesActionPerformed
        // TODO add your handling code here:
        this.setTitle("Gestión de almacén Clientes modificaciones");
         hab_menu(false);
        habilitar(true,0);
        jTextFieldCodigo.grabFocus();
    }//GEN-LAST:event_ModificacionesActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        habilitar(false,1);
        jButtonSalir.setEnabled(false);
        borrar();
        this.setTitle("Gestión de almacén Clientes");
        hab_menu(true);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jMenuItemConsultaPorCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaPorCodigoActionPerformed
        // TODO add your handling code here:
        jTextFieldCodigo.setEnabled(true);
        this.setTitle("Gestión de almacén Clientes consultas");
        hab_menu(false);
    }//GEN-LAST:event_jMenuItemConsultaPorCodigoActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

       // Conexion.ejecutarInforme().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        //Conexion.ejecutarInformeGrafico().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        entre_code ec = new entre_code(this);
        this.setEnabled(false);
        ec.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    private void habilitar(boolean b, int i){
        if(i == 1){
            jTextFieldCodigo.setEnabled(b);
            jTextFieldNIF.setEnabled(b);
            jTextFieldNombre.setEnabled(b);
            jTextFieldApellidos.setEnabled(b);
            jTextFieldDomicilio.setEnabled(b);
            jTextFieldCP.setEnabled(b);
            jTextFieldLocalidad.setEnabled(b);
            jTextFieldTelefono.setEnabled(b);
            jTextFieldMovil.setEnabled(b);
            jTextFieldFax.setEnabled(b);
            jTextFieldEmail.setEnabled(b);
            jButtonAceptar.setEnabled(b);
            jButtonCancelar.setEnabled(b);
        }else if(i == 0){
            jTextFieldCodigo.setEnabled(b);
            jTextFieldNIF.setEnabled(!b);
            jTextFieldNombre.setEnabled(!b);
            jTextFieldApellidos.setEnabled(!b);
            jTextFieldDomicilio.setEnabled(!b);
            jTextFieldCP.setEnabled(!b);
            jTextFieldLocalidad.setEnabled(!b);
            jTextFieldTelefono.setEnabled(!b);
            jTextFieldMovil.setEnabled(!b);
            jTextFieldFax.setEnabled(!b);
            jTextFieldEmail.setEnabled(!b);
           
        }else if(i == 2){
            jButtonAceptar.setEnabled(b);
            jButtonCancelar.setEnabled(b);
        }
    }
    public void hab_menu(boolean b){
        Altas.setEnabled(b);
        Bajas.setEnabled(b);
        Modificaciones.setEnabled(b);
        jButtonSalir.setEnabled(!b);
        jMenuConsulta.setEnabled(b);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Formulario(padre).setVisible(true);
        });
    }
     protected void processWindowEvent(java.awt.event.WindowEvent e) {

        super.processWindowEvent(e);
        if (e.getID() == java.awt.event.WindowEvent.WINDOW_CLOSING) {
            padre.setEnabled(true);
            padre.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Altas;
    private javax.swing.JMenuItem Bajas;
    private javax.swing.JMenuItem Modificaciones;
    private javax.swing.JMenuItem Volver;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFax;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelMovil;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemConsultaPorCodigo;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFax;
    private javax.swing.JTextField jTextFieldLocalidad;
    private javax.swing.JTextField jTextFieldMovil;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldNIF_letra;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
