/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario_con_bd;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author alumno
 */
public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    
    static javax.swing.JFrame padre;
    public Pedidos(javax.swing.JFrame padre) throws SQLException {
        ut = new Utilidades();
        cox = new Conexion();
        this.padre = padre;
        initComponents();
        jScrollPane1.setVisible(false);
        
    }
    
    Utilidades ut;
    Conexion cox;
    String tabla,cod;
    Modelo model;
    float total;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelNIF = new javax.swing.JLabel();
        jTextFieldNIF = new javax.swing.JTextField();
        jTextFieldNIF_letra = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelDomicilio = new javax.swing.JLabel();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jLabelCP = new javax.swing.JLabel();
        jTextFieldCP = new javax.swing.JTextField();
        jLabelLocalidad = new javax.swing.JLabel();
        jTextFieldLocalidad = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelMovil = new javax.swing.JLabel();
        jTextFieldMovil = new javax.swing.JTextField();
        jLabelFax = new javax.swing.JLabel();
        jTextFieldFax = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelArticulo = new javax.swing.JLabel();
        jTextFieldArticulo = new javax.swing.JTextField();
        jLabelDescripcion = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabelUnidades = new javax.swing.JLabel();
        jTextFieldUnidades = new javax.swing.JTextField();
        Stock = new javax.swing.JLabel();
        jTextFieldStock = new javax.swing.JTextField();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabelImporte = new javax.swing.JLabel();
        jTextFieldImporte = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonCancelarPedido = new javax.swing.JButton();
        jButtonCancelartodo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonFactura = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuProveedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuVolver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de almacén Pedidos");
        setResizable(false);

        jLabelCodigo.setText("Código");

        jTextFieldCodigo.setToolTipText("");
        jTextFieldCodigo.setEnabled(false);
        jTextFieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyTyped(evt);
            }
        });

        jLabelNIF.setText("N.I.F.");

        jTextFieldNIF.setEnabled(false);

        jTextFieldNIF_letra.setEditable(false);
        jTextFieldNIF_letra.setToolTipText("");
        jTextFieldNIF_letra.setEnabled(false);

        jLabelNombre.setText("Nombre");

        jTextFieldNombre.setEnabled(false);

        jLabelApellidos.setText("Apellidos");

        jTextFieldApellidos.setToolTipText("");
        jTextFieldApellidos.setEnabled(false);

        jLabelDomicilio.setText("Domicilio");

        jTextFieldDomicilio.setEnabled(false);

        jLabelCP.setText("C.P.");

        jTextFieldCP.setEnabled(false);

        jLabelLocalidad.setText("Localidad");

        jTextFieldLocalidad.setEnabled(false);

        jLabelTelefono.setText("Teléfono");

        jTextFieldTelefono.setEnabled(false);

        jLabelMovil.setText("Móvil");

        jTextFieldMovil.setEnabled(false);

        jLabelFax.setText("Fax");

        jTextFieldFax.setEnabled(false);

        jLabelEmail.setText("Email");

        jTextFieldEmail.setEnabled(false);

        jLabelTotal.setText("Total");

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setEnabled(false);

        jLabel1.setText("------------------------------------------------------------------------------------------------");

        jLabelArticulo.setText("Artículo");

        jTextFieldArticulo.setEnabled(false);
        jTextFieldArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldArticuloKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldArticuloKeyPressed(evt);
            }
        });

        jLabelDescripcion.setText("Descripción");

        jTextFieldDescripcion.setEnabled(false);

        jLabelUnidades.setText("Unidades");

        jTextFieldUnidades.setEnabled(false);
        jTextFieldUnidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUnidadesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldUnidadesKeyReleased(evt);
            }
        });

        Stock.setText("Stock");

        jTextFieldStock.setEnabled(false);

        jLabelPrecio.setText("Precio");

        jTextFieldPrecio.setEnabled(false);

        jLabelImporte.setText("Importe");

        jTextFieldImporte.setEnabled(false);

        jButtonAceptar.setMnemonic('a');
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setEnabled(false);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonSalir.setMnemonic('s');
        jButtonSalir.setText("Salir");
        jButtonSalir.setEnabled(false);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonCancelarPedido.setMnemonic('c');
        jButtonCancelarPedido.setText("Cancelar pedido");
        jButtonCancelarPedido.setEnabled(false);
        jButtonCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarPedidoActionPerformed(evt);
            }
        });

        jButtonCancelartodo.setMnemonic('o');
        jButtonCancelartodo.setText("Cancelar todo");
        jButtonCancelartodo.setEnabled(false);
        jButtonCancelartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelartodoActionPerformed(evt);
            }
        });

        jButton1.setMnemonic('.');
        jButton1.setText("...");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Stock", "Precio"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonFactura.setMnemonic('f');
        jButtonFactura.setText("Factura");
        jButtonFactura.setEnabled(false);
        jButtonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacturaActionPerformed(evt);
            }
        });

        jMenu2.setMnemonic('p');
        jMenu2.setText("Pedidos");
        jMenu2.setToolTipText("");

        jMenuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCliente.setMnemonic('c');
        jMenuCliente.setText("Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCliente);

        jMenuProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuProveedor.setMnemonic('p');
        jMenuProveedor.setText("Proveedor");
        jMenuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProveedorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuProveedor);
        jMenu2.add(jSeparator1);

        jMenuVolver.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuVolver.setMnemonic('v');
        jMenuVolver.setText("Volver");
        jMenuVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVolverActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuVolver);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmail)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelUnidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldUnidades)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Stock)
                                            .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelPrecio)
                                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelImporte)
                                                    .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonCancelarPedido)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonCancelartodo))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelDescripcion)
                                            .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonFactura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelTotal)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldApellidos)
                                    .addComponent(jTextFieldDomicilio)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCodigo)
                                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelNIF)
                                                .addGap(55, 55, 55))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldNIF_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNombre)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabelApellidos)
                                    .addComponent(jLabelDomicilio)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCP)
                                            .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelLocalidad)
                                            .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTelefono)
                                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelMovil)
                                            .addComponent(jTextFieldMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelFax)
                                            .addComponent(jTextFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(380, 380, 380)
                                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jLabelNIF)
                    .addComponent(jLabelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNIF_letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabelApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelDomicilio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCP)
                    .addComponent(jLabelLocalidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jLabelMovil)
                    .addComponent(jLabelFax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArticulo)
                    .addComponent(jLabelDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jTextFieldDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUnidades)
                    .addComponent(Stock)
                    .addComponent(jLabelPrecio)
                    .addComponent(jLabelImporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelarPedido)
                    .addComponent(jButtonCancelartodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void borrar(){
           // TODO add your handling code here:
        jTextFieldCodigo.setText("");
        jTextFieldNIF.setText("");
        jTextFieldNIF_letra.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellidos.setText("");
        jTextFieldDomicilio.setText("");
        jTextFieldCP.setText("");
        jTextFieldLocalidad.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldMovil.setText("");
        jTextFieldFax.setText("");
        jTextFieldEmail.setText("");
        jTextFieldCodigo.grabFocus();
        jTextFieldArticulo.setText("");
        jTextFieldUnidades.setText("");
        jTextFieldStock.setText("");
        jTextFieldDescripcion.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldImporte.setText("");
        jTextFieldTotal.setText("");
    }
    private void jTextFieldCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyTyped
        // TODO add your handling code here:
        ut.num_carac(jTextFieldCodigo,6, evt);
    }//GEN-LAST:event_jTextFieldCodigoKeyTyped

    private void jTextFieldCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            ut.ceros(jTextFieldCodigo, 6);
            String code = jTextFieldCodigo.getText();  
                  try {
                      if(this.getTitle().equals("Gestión de Almacén Pedidos cliente")){
                          tabla = "Clientes";
                          cod = "Cli";
                      }else{
                          tabla = "Proveedores";
                          cod ="Prov";
                      }
                    if(cox.Consultar(code,tabla,cod)){
                        consultar(code);
                        jTextFieldArticulo.setEnabled(true);
                        jTextFieldCodigo.setEnabled(false);
                        jButtonCancelartodo.setEnabled(true);
                        jButton1.setEnabled(true);
                         try {
                            rellenartabla();
                         } catch (SQLException ex) {
                            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Este usuario no existe");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            
        }
    }//GEN-LAST:event_jTextFieldCodigoKeyPressed
    private void consultar(String code) throws SQLException{
        ResultSet rs= cox.obtener(code,tabla,cod);
                        rs.next();
             
                        jTextFieldNIF.setText(rs.getString("NIF").substring(0,8));
                        jTextFieldNIF_letra.setText(rs.getString("NIF").substring(8));
                        jTextFieldNombre.setText(rs.getString("Nombre"));
                        jTextFieldApellidos.setText(rs.getString("Apellidos"));
                        jTextFieldDomicilio.setText(rs.getString("Domicilio"));
                        jTextFieldCP.setText(rs.getString("CP"));
                        jTextFieldLocalidad.setText(rs.getString("Localidad"));
                        jTextFieldTelefono.setText(rs.getString("Telefono"));
                        jTextFieldFax.setText(rs.getString("Fax"));
                        jTextFieldMovil.setText(rs.getString("Movil"));
                        jTextFieldEmail.setText(rs.getString("Email"));
                        jTextFieldTotal.setText(Float.toString(rs.getFloat("Total")));
                        total = rs.getFloat("Total");
    }
    private void jMenuVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVolverActionPerformed
        // TODO add your handling code here:
        padre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuVolverActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        // TODO add your handling code here:
        this.setTitle("Gestión de Almacén Pedidos cliente");
        jTextFieldCodigo.setEnabled(true);
        jTextFieldCodigo.grabFocus();
        jButtonSalir.setEnabled(true);
        jMenu2.setEnabled(false);
        botnombre();
        
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProveedorActionPerformed
        // TODO add your handling code here:
         this.setTitle("Gestión de Almacén Pedidos proveedor");
         jTextFieldCodigo.setEnabled(true);
         jTextFieldCodigo.grabFocus();
         jButtonSalir.setEnabled(true);
         jMenu2.setEnabled(false);
         botnombre();
    }//GEN-LAST:event_jMenuProveedorActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        
        if(jButtonFactura.isEnabled()){
            if(JOptionPane.showConfirmDialog(this,"¿Quieres salir sin guardar los pedidos?","Antes de irte...", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
                try {
                    cox.comit(false);
                    habilitar(false);
                    borrar();
                    jButtonSalir.setEnabled(false);
                    jMenu2.setEnabled(true);
                    jTextFieldCodigo.setEnabled(false);
                    jTextFieldUnidades.setEnabled(false);
                    jTextFieldArticulo.setEnabled(false);
                    jScrollPane1.setVisible(false);
                    jButton1.setEnabled(false);
                    jButtonAceptar.setEnabled(false);
                    jButtonFactura.setEnabled(false);
                } catch (SQLException ex) {
                    Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            habilitar(false);
            borrar();
            jButtonSalir.setEnabled(false);
            jMenu2.setEnabled(true);
            jTextFieldCodigo.setEnabled(false);
            jTextFieldUnidades.setEnabled(false);
            jTextFieldArticulo.setEnabled(false);
            jScrollPane1.setVisible(false);
            jButton1.setEnabled(false);
            jButtonAceptar.setEnabled(false);
            jButtonFactura.setEnabled(false);

        }
        
        
        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldArticuloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldArticuloKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                ut.ceros(jTextFieldArticulo, 6);
                if(cox.ConsultarArt(jTextFieldArticulo.getText())){
                    ResultSet rs = cox.obtenerArt(jTextFieldArticulo.getText());
                    rs.next();
                    jTextFieldArticulo.setEnabled(false);
                    jButtonCancelarPedido.setEnabled(true);
                    jTextFieldUnidades.setEnabled(true);
                    jTextFieldUnidades.grabFocus();
                    jTextFieldDescripcion.setText(rs.getString("Descripcion"));
                    jTextFieldStock.setText(Integer.toString(Math.round(rs.getFloat("Stock"))));
                    jButton1.setEnabled(false);
                    if(this.getTitle().equals("Gestión de Almacén Pedidos cliente")){
                        jTextFieldPrecio.setText(Float.toString(rs.getFloat("Precio_venta")));
                    }else{
                         jTextFieldPrecio.setText(Float.toString(rs.getFloat("Precio_compra")));
                    }            
                }else{
                    JOptionPane.showMessageDialog(this, "Este artículo no existe");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTextFieldArticuloKeyPressed

    private void jTextFieldUnidadesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUnidadesKeyReleased
        // TODO add your handling code here:
        
      if(!ut.comprobar(jTextFieldUnidades, "Numero",1)){
         if(!(jTextFieldUnidades.getText().equals("")&&jTextFieldUnidades.getText().equals("0"))){
            int unidades = Integer.parseInt(jTextFieldUnidades.getText());
            int stock = Integer.parseInt(jTextFieldStock.getText());
            if(this.getTitle().equals("Gestión de Almacén Pedidos cliente")&&unidades>stock){
                JOptionPane.showMessageDialog(this, "no hay stock suficiente");
                jTextFieldUnidades.setText(Integer.toString(stock));
            }else if(this.getTitle().equals("Gestión de Almacén Pedidos proveedor")&&unidades>100){
                JOptionPane.showMessageDialog(this, "El límite de compra de una sola vez es 100 unidades");
                jTextFieldUnidades.setText("100");
                unidades = Integer.parseInt(jTextFieldUnidades.getText());
            }
            jTextFieldImporte.setText(String.valueOf((float)unidades*Float.parseFloat(jTextFieldPrecio.getText())));
            jTextFieldTotal.setText(Float.toString(Float.parseFloat(jTextFieldImporte.getText())+total));
            }
        }
    }//GEN-LAST:event_jTextFieldUnidadesKeyReleased

    private void jTextFieldArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldArticuloKeyTyped
        // TODO add your handling code here:         
         ut.num_carac(jTextFieldArticulo,6, evt);
         
    }//GEN-LAST:event_jTextFieldArticuloKeyTyped

    private void jButtonCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarPedidoActionPerformed
        // TODO add your handling code here:
        jTextFieldArticulo.setText("");
        jTextFieldUnidades.setEnabled(false);
        jTextFieldUnidades.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldImporte.setText("");
        jTextFieldStock.setText("");
        jTextFieldDescripcion.setText("");
        jTextFieldArticulo.setEnabled(true);
        jTextFieldArticulo.grabFocus();
        jButtonCancelarPedido.setEnabled(false);
        jButtonAceptar.setEnabled(false);
        jTable1.setEnabled(true);
        if(!jScrollPane1.isVisible()){
            jButton1.setEnabled(true);
        }
        jTextFieldTotal.setText(Float.toString(total));
    }//GEN-LAST:event_jButtonCancelarPedidoActionPerformed

    private void jButtonCancelartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelartodoActionPerformed
        // TODO add your handling code here:
       
        if(jButtonFactura.isEnabled()){
            if(JOptionPane.showConfirmDialog(this,
            "¿Quieres descartar los pedidos hechos hasta ahora?","Antes de irte...", 
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
                try {
                    cox.comit(false);
                    jButtonCancelartodo.setEnabled(false);
                    borrar();
                    jTextFieldArticulo.setEnabled(false);
                    jTextFieldCodigo.setEnabled(true);
                    jTextFieldUnidades.setEnabled(false);
                    jButtonCancelarPedido.setEnabled(false);
                    jButton1.setEnabled(false);
                    jScrollPane1.setVisible(false);
                    jButtonFactura.setEnabled(false);
                    jButtonAceptar.setEnabled(false);
                } catch (SQLException ex) {
                    Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                jButtonFactura.grabFocus();
            }
            
        }else{
            jButtonCancelartodo.setEnabled(false);
            borrar();
            jTextFieldArticulo.setEnabled(false);
            jTextFieldCodigo.setEnabled(true);
            jTextFieldUnidades.setEnabled(false);
            jButtonCancelarPedido.setEnabled(false);
            jButton1.setEnabled(false);
            jScrollPane1.setVisible(false);
            jButtonFactura.setEnabled(false);
            jButtonAceptar.setEnabled(false);
        }
        
        
        
    }//GEN-LAST:event_jButtonCancelartodoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setVisible(true);
        this.pack();
        this.revalidate();
        this.repaint();
        jButton1.setEnabled(false);
        jTextFieldArticulo.grabFocus();
        
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacturaActionPerformed
        // TODO add your handling code here:
        jButtonFactura.setEnabled(false);
        try {
            cox.comit(true);
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextFieldArticulo.setEnabled(false);
        jTextFieldCodigo.setEnabled(true);
        jTextFieldCodigo.grabFocus();
        jButton1.setEnabled(false);
        jScrollPane1.setVisible(false);
        jButtonCancelartodo.setEnabled(false);
        borrar();
    }//GEN-LAST:event_jButtonFacturaActionPerformed

    private void jTextFieldUnidadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUnidadesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(ut.comprobar(jTextFieldUnidades, "Numero", 1)||jTextFieldUnidades.getText().equals("0")){
                JOptionPane.showMessageDialog(this, "Introduce un número mayor a 0");
            }else{
                jButtonAceptar.setEnabled(true);
                jTextFieldUnidades.setEnabled(false);
                jTable1.setEnabled(false);
                jButtonAceptar.grabFocus();

            }
        }
            
            
        
    }//GEN-LAST:event_jTextFieldUnidadesKeyPressed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        jButtonFactura.setEnabled(true);
        jButtonAceptar.setEnabled(false);
        jButtonCancelarPedido.setEnabled(false);
        total = Float.parseFloat(jTextFieldTotal.getText());
        String s = null;
        String s2 = null;
        float Stock = 0;
        if(this.getTitle().equals("Gestión de Almacén Pedidos cliente")){
            Stock = Float.parseFloat(jTextFieldStock.getText()) - Float.parseFloat(jTextFieldUnidades.getText());
            s = "Clientes";
            s2 = "CodigoCli";
        }else{
            Stock = Float.parseFloat(jTextFieldStock.getText()) + Float.parseFloat(jTextFieldUnidades.getText());
            s = "Proveedores";
            s2 = "CodigoProv";
        }
        try {
            cox.modificarArt(jTextFieldArticulo.getText(), Stock);
            cox.modificarTot(jTextFieldCodigo.getText(),Float.parseFloat(jTextFieldTotal.getText()),s,s2);
            if(s.equals("Clientes")){
                 cox.pedidos(jTextFieldCodigo.getText(), null, jTextFieldArticulo.getText(),Integer.parseInt(jTextFieldUnidades.getText()));
            }else{
                 cox.pedidos(null, jTextFieldCodigo.getText(), jTextFieldArticulo.getText(),Integer.parseInt(jTextFieldUnidades.getText()));
            }
            
           
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
         jTextFieldArticulo.setEnabled(true);
         jTextFieldArticulo.grabFocus();
         jTextFieldPrecio.setText("");
         jTextFieldUnidades.setText("");
         jTextFieldImporte.setText("");
         jTextFieldStock.setText("");
         jTextFieldDescripcion.setText("");
         if(!jScrollPane1.isVisible()){
             jButton1.setEnabled(true);
         }
         
         jTable1.setEnabled(true);
        try {
            rellenartabla();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
       
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        try{
        if(jTable1.isEnabled()){
        int Selected = jTable1.getSelectedRow();
        jTextFieldArticulo.setText((String) jTable1.getModel().getValueAt(Selected, 0));       
        ResultSet rs = null;
            rs = cox.obtenerArt(jTextFieldArticulo.getText());
            rs.next();
             jTextFieldArticulo.setEnabled(false);
                    jButtonCancelarPedido.setEnabled(true);
                    jTextFieldUnidades.setEnabled(true);
                    jTextFieldUnidades.grabFocus();
                    jTextFieldDescripcion.setText(rs.getString("Descripcion"));
                    jTextFieldStock.setText(Integer.toString(Math.round(rs.getFloat("Stock"))));
                    if(this.getTitle().equals("Gestión de Almacén Pedidos cliente")){
                        jTextFieldPrecio.setText(Float.toString(rs.getFloat("Precio_venta")));
                    }else{
                         jTextFieldPrecio.setText(Float.toString(rs.getFloat("Precio_compra")));
                    } 
        }
         boolean b=false;
        if(!ut.comprobar(jTextFieldUnidades, "Numero",1)){
         if(!(jTextFieldUnidades.getText().equals("")&&jTextFieldUnidades.getText().equals("0"))){
            int unidades = Integer.parseInt(jTextFieldUnidades.getText());
            int stock = Integer.parseInt(jTextFieldStock.getText());
            if(this.getTitle().equals("Gestión de Almacén Pedidos cliente")&&unidades>stock){
                JOptionPane.showMessageDialog(this, "no hay stock suficiente");
                jTextFieldUnidades.setText(Integer.toString(stock));
            }else if(this.getTitle().equals("Gestión de Almacén Pedidos proveedor")&&unidades>100){
                JOptionPane.showMessageDialog(this, "El límite de compra de una sola vez es 100 unidades");
                jTextFieldUnidades.setText("100");
                unidades = Integer.parseInt(jTextFieldUnidades.getText());
            }
            jTextFieldImporte.setText(String.valueOf((float)unidades*Float.parseFloat(jTextFieldPrecio.getText())));
            jTextFieldTotal.setText(Float.toString(Float.parseFloat(jTextFieldImporte.getText())+total));
            }
        }
        } catch (Exception ex) {
           // Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
       
                   
    }//GEN-LAST:event_jTable1MousePressed
    private void habilitar(boolean b){
        jButtonCancelarPedido.setEnabled(b);
        jButtonCancelartodo.setEnabled(b);
        this.setTitle("Gestión de Almacén Pedidos");
    }
    private void botnombre(){
        if(this.getTitle().equals("Gestión de Almacén Pedidos cliente")){
                jButtonFactura.setText("Factura");
            }else{
                jButtonFactura.setText("Finalizar");
            }
    }
    private void rellenartabla() throws SQLException{
         ArrayList<String> s = cox.listarart(this.getTitle());
        this.model = new Modelo(s);
        jTable1.setModel(model.rellenar());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Pedidos(padre).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
     protected void processWindowEvent(java.awt.event.WindowEvent e) {

        super.processWindowEvent(e);
        if (e.getID() == java.awt.event.WindowEvent.WINDOW_CLOSING) {
            padre.setEnabled(true);
            padre.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Stock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelarPedido;
    private javax.swing.JButton jButtonCancelartodo;
    private javax.swing.JButton jButtonFactura;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelArticulo;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFax;
    private javax.swing.JLabel jLabelImporte;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelMovil;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelUnidades;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuProveedor;
    private javax.swing.JMenuItem jMenuVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldArticulo;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFax;
    private javax.swing.JTextField jTextFieldImporte;
    private javax.swing.JTextField jTextFieldLocalidad;
    private javax.swing.JTextField jTextFieldMovil;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldNIF_letra;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldUnidades;
    // End of variables declaration//GEN-END:variables
}
